### ISSUE TITLE
Improve CEA installation script

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/create-evergreen-app#12]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

In relation to #11 , the installation script right now is a little hacky and duct taped together (IMO), but it should get the job done. 

## Details
1. [x] It wouldn't have to clone from `git`, the contents could be derived from the package contents itself (0.4.0)
1. [x] Running `npm install` by default (0.3.0)
1. [x]  Actually moving into the new directory would be pretty nice. 💯 (0.3.0)

For some good inspiration, see how it is done by [Create React App](https://github.com/facebook/create-react-app)
- https://github.com/facebook/create-react-app/blob/next/tasks/cra.js
- https://github.com/facebook/create-react-app/blob/next/packages/create-react-app/createReactApp.js

**Comment by dariusstrasel** [comment]
It would probably be helpful to use the [node.js path module](https://nodejs.org/api/path.html) to introduce stability around POSIX and Window's based directories/files. I'm not sure if this is a problem atm for the script, but using said module would help prevent one from occuring, as opposed to using string literals which make assumptions about path invariants.

**Comment by thescientist13** [comment]
Cross platform compatibility with this kind of ad-hoc scripting definitely needs to be kept en eye on.  I have some windows VMs so it would be good to double check there.

@hutchgrant 
Do you have a VM to test this script with by chance?

**Comment by thescientist13** [comment]
@hutchgrant 
If you want to open a PR for the git issue, then we can consider this closed out!  👍
