### ISSUE TITLE
[Test] - Add Custom Elements v1 Polyfill and additional browsers for karma configuration

### ISSUE THREAD

**Issue by garyvh2** [ProjectEvergreen/create-evergreen-app#37]
## Type of Change
- [x] New Feature Request
- [ ] Documentation
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
Right now there's only one browser to be tested `ChromiumHeadlessConfigured`, it would be nice to have `karma-ie-launcher`, `karma-edge-launcher` and `karma-firefox-launcher` out of the box.

In order to accomplish that, it's necessary to include the relevant `web components js` Polyfill for both browsers.

## Details
- It's necessary to add `karma-ie-launcher`, `karma-edge-launcher` and `karma-firefox-launcher` pluggins included on the karma configuration file and browsers list.
- For the Polyfills have a look at this example https://github.com/open-wc/open-wc/blob/master/packages/generator-open-wc/generators/testing-karma/templates/static/karma.conf.js#L25-L33 provided by @dakmor on the Polymer community

Tell me if you require additional information

**Comment by thescientist13** [comment]
Thanks for raising this issue @garyvh2 !

Adding examples for other browsers is a good idea, so will definitely put something together on my end.
