### ISSUE TITLE
Proposal: Move configuration files into separate config directory

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/create-evergreen-app#46]
## Type of Change
- [x] New Feature Request
- [ ] Documentation
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
There are over 10 configuration files in the base directory and it makes new applications generated by create-evergreen-app a bit messy to look at. I propose moving all necessary configuration files(webpack, eslint, postcss, karma, babel) into a seperate config folder in the root directory.

## Details
With the configuration files organized within their own subdirectory, it will be much cleaner, plus it's simply much easier for the install script to deal with.  All the script needs to do is copy the src, docs, and config folders into a newly generated application. Like this:

![config_organize_propsal](https://user-images.githubusercontent.com/1429612/48110874-b9dc8a00-e21c-11e8-9c55-253cf8d1032b.png)

**Comment by thescientist13** [comment]
Thanks for opening this proposal @hutchgrant 👍 

True, there are a number of configuration files, but such is the state of modern frontend development.  

I like to keep things in the root for a few reasons:
1. I like keeping things flatter where possible, which I think fits the spirit of this project in the context of a starter app.  
1. Most of these tools are configured to look for configuration files in the root of the project by default (Karma, Babel, eslint, etc).  
1. Looking for things In the root is likely also the case for IDEs and also keeps npm scripts shorter by not having additional pathing clogging up the script. 
1. The general convention is to keep them in the root directory, which is what has come to enable the simplicity of interoperability of the above three points (IMO).

That said, if there are ways to _reduce_ the configuration files, that would be even better!  Open to any recommendations around that 💯

**Comment by hutchgrant** [comment]
> The general convention is to keep them in the root directory

Create React App does not do this. It's actually all consolidated under react-scripts package, but when you run the eject script you'll see all the configs(webpack, jest, env, paths) are placed in a config folder.

You're right most these tools do expect the root directory as the **default** but most if not all do have the option to configure a different path to a config file. Some we could even add directly to the package.json and do not even need a directory. E.g. browserlist and babel can both be added to the package.json.

**Comment by thescientist13** [comment]
> Create React App does not do this

Understood, they probably reuse those scripts in many other projects.  But again, having them in a different folder leads to additional maintenance / overhead on our part as result (most of the points I raised).

Let me think about it some more though.

**Comment by thescientist13** [comment]
Also, this is from one of the maintainers of CRA (Dan Abramov), so it really just comes down to preference, tbh
https://twitter.com/dan_abramov/status/1027245759232651270?lang=en

**Comment by hutchgrant** [comment]
Further to the point, the alternative of copying the entire root directory(instead of specific folders, and the README), then removing files we don't need, is not an efficient, practical, solution. The correct solution is to use a config folder instead. Here's why:

Problem 1)

>  Cannot copy contents into a subdirectory of itself.

 We cannot simply copy ./create-react-app into a ./my-app if we run node tasks/cea-install.js for a test from the project's working directory. Well that's fine, you're thinking, we'll just do it from outside the working directory. Well that's certainly not ideal for the project's unit tests.

Problem 2) With the wildcard copy it will also include node_modules and of course this takes a lot more time than necessary to copy something that we will just remove anyway.

Problem 3) It involves more code, etc.

Problem 4) Given the above, the alternative way to do it, with a copy function, is to create a whitelist of files specifically to copy. This will be annoying if we add another configuration file down the line or remove one! Whereas if the configs are in the config directory, you'll be able to add/remove them without affecting the install script!

Therefore, a config directory is the most simple, efficient, correct, way of doing it.

**Comment by thescientist13** [comment]
Not sure if there's anything to do at this point given all the template / script refactoring.  

At this point, I don't think I would be up for making more refactoring changes to the project or installer unless, as I'm thinking we should try and address more "features" like:
- state management
- routing


That said, I am fine to allow minor improvements to installation experience, like #79 or #85 for now.

**Comment by hutchgrant** [comment]
I suppose I'll close this but my personal preference is that configs should be organized differently but that's fine.
