### ISSUE TITLE
npx install failing - cannot spawn child process

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/create-evergreen-app#57]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
Related to #54 , it looks like I had a local installation of create-evergreen-app, that was messing with things.  I can now reproduce this across OSX, Linux, and Windows.
```shell
$ npx create-evergreen-app
npx: installed 3 in 1.49s
Cannot find module 'cross-spawn'
$ npx create-evergreen-app my-app
npx: installed 3 in 1.427s
Cannot find module 'cross-spawn'
$ npx -D -p  create-evergreen-app my-app
npx: installed 203 in 5.868s
npx: command not found: create-evergreen-app
$ npx -D -p create-evergreen-app create-evergreen-app  my-app
npx: installed 203 in 4.763s
npx: command not found: create-evergreen-app
$ npx create-evergreen-app create-evergren-app my-app
npx: installed 3 in 1.47s
Cannot find module 'cross-spawn'
```

## Details
Maybe we need npm install and npx?  I was hoping npx would replace the need for a global install.

**Comment by thescientist13** [comment]
I think the real solution is not use anything in _cea-install.js_ that is not part of the standard NodeJS API.

Will look into testing child-process again.

**Comment by hutchgrant** [comment]
CRA [uses cross-spawn](https://github.com/facebook/create-react-app/blob/master/packages/create-react-app/package.json) and it works fine from npx. I think it has to do with being a devdependency in CEA and CRA uses it as a regular dependency

So the solution is to create separate dependencies for the package.json for the CEA vs the application it generates.  This would obviously cause the unit tests to fail and would have to be rewritten to spawn a new application and test based on that. Which may actually be beneficial anyways

Or you can create and include it as a separate dev-utils package, which uses cross-spawn as just a regular depency, which CRA also does with react-scripts.

Also cross-spawn is[ a cross-platform replacement](https://www.npmjs.com/package/cross-spawn) for [child_process spawn](https://nodejs.org/api/child_process.html) which has issues on windows.  It's probably a better idea to continue using it, unless you have any other suggestions.

**Comment by thescientist13** [comment]
tested by ignoring that file, and now got this
```
$ rm -rf my-app/ && npx github:ProjectEvergreen/create-evergreen-app#775a131b091607f7628990282d4dbcd9c8238930 my-app
npx: installed 3 in 5.215s
-------------------------------------------------------
Welcome to Create Evergreen App ♻️
-------------------------------------------------------
Preparing project directory...
Initializing npm dependencies...
Copying project files...
File doesn't exist! : /Users/owenbuckley/.npm/_npx/72803/lib/node_modules/create-evergreen-app/package-lock.json
```

😖 

Not sure if `npx` will be helpful testing outside of **npm**?  I guess since `npx create-evergreen-app` is already broken, no harm in pushing a new version even if it doesn't work?  Seems like it will just be a little trial and error, but I think it's close.  ❓
