### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by hutchgrant** [ProjectEvergreen/create-evergreen-app#74]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Dependencies favicons-webpack-plugin and webpack-dev-server need to be updated, npm audit threw a warning about vulnerabilities.

## Details

```bash
npm audit

found 6 vulnerabilities (3 low, 2 moderate, 1 high) in 14929 scanned packages
```

**Comment by thescientist13** [comment]
oh, I thought this sounded familiar.  duplicate of #70 ?
